version: '3'
services:
  backend:
    image: seojaeeun/backend:${DOCKER_IMAGE_TAG}
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
  frontend:
    image: seojaeeun/frontend:${DOCKER_IMAGE_TAG}
    ports:
      - "80:80"